// <auto-generated />
using System;
using ExampleApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExampleApi.Migrations
{
    [DbContext(typeof(WorkersContext))]
    [Migration("20210121111141_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ExampleApi.Models.Workers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int?>("WorkersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkersId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("ExampleApi.Models.Workers", b =>
                {
                    b.HasOne("ExampleApi.Models.Workers", null)
                        .WithMany("workers")
                        .HasForeignKey("WorkersId");
                });

            modelBuilder.Entity("ExampleApi.Models.Workers", b =>
                {
                    b.Navigation("workers");
                });
#pragma warning restore 612, 618
        }
    }
}
